# Generated by Django 5.0.1 on 2024-01-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_directory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('registered_user', 'unregistered_user')},
        ),
    ]
