# Generated by Django 5.0.1 on 2024-01-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_directory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
    ]
